import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { SmoothScrollProvider } from "@/components/providers/SmoothScrollProvider";
import BackgroundCanvas from "@/components/sections/bg/BackgroundCanvas";
import BubblesComponent from "@/components/sections/bubbles/BubblesComponent";
import SideMenu from "@/components/sections/sideMenu/SideMenu";
import ViewCanvas from "@/components/ViewCanvas";

const creamCake = localFont({
  variable: "--font-cream-cake",
  src: "../../public/font/Cream Cake.otf",
});

const poppins = localFont({
  variable: "--font-poppins",
  src: "../../public/font/poppins-extrabold.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`${poppins.variable} ${creamCake.variable} scrollbar scrollbar-none overflow-x-hidden antialiased`}
      >
        <Header />
        <SideMenu />
        <BackgroundCanvas />
        <SmoothScrollProvider>
          <main className="bg-secondary font-poppins">
            <BubblesComponent />
            {children}
            <ViewCanvas />
          </main>
          <Footer />
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
