import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { SmoothScrollProvider } from "@/components/providers/SmoothScrollProvider";
import Header from "@/components/Header";
import ViewCanvas from "@/components/ViewCanvas";

const creamCake = localFont({
  variable: "--font-cream-cake",
  src: "../../public/font/Cream Cake.otf",
});

const poppins = localFont({
  variable: "--font-poppins",
  src: "../../public/font/poppins-extrabold.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${creamCake.variable} antialiased overflow-x-hidden bg-secondary`}
      >
        <SmoothScrollProvider>
          <Header />
          <main>
            {children}
            <ViewCanvas />
          </main>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
